### ISSUE TITLE
Create real time dashboard does not work

### ISSUE THREAD

**Issue by evelant** [rakam-io/rakam-ui#1]
When clicking create:

Error in console, 500 Internal Server Error

Request details:
Url: `https://my_host//realtime/create?master_key=my_key`
Payload: `{"table_name":"checked_off","collections":["checked off a task"],"name":"checked off","measures":[{"aggregation":"count","column":"task_type"}],"dimensions":[]}`

Response: `{"error":"Error processing request.","error_code":500}`

**Comment by evelant** [comment]
Logs from my server
```
2016-12-02T00:09:04.628843+00:00 app[web.1]: 2016-12-02T00:09:04.628Z   ERROR   nioEventLoopGroup-4-12  org.rakam.server.http.HttpServer        Error while processing request
2016-12-02T00:09:04.628845+00:00 app[web.1]: com.facebook.presto.sql.parser.ParsingException: line 1:61: no viable alternative at input 'FROM'
2016-12-02T00:09:04.628847+00:00 app[web.1]:    at com.facebook.presto.sql.parser.SqlParser$1.syntaxError(SqlParser.java:45)
2016-12-02T00:09:04.628847+00:00 app[web.1]:    at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
2016-12-02T00:09:04.628848+00:00 app[web.1]:    at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:566)
2016-12-02T00:09:04.628849+00:00 app[web.1]:    at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:308)
2016-12-02T00:09:04.628850+00:00 app[web.1]:    at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:145)
2016-12-02T00:09:04.628851+00:00 app[web.1]:    at com.facebook.presto.sql.parser.SqlBaseParser.selectItem(SqlBaseParser.java:4713)
2016-12-02T00:09:04.628852+00:00 app[web.1]:    at com.facebook.presto.sql.parser.SqlBaseParser.querySpecification(SqlBaseParser.java:3693)
2016-12-02T00:09:04.628854+00:00 app[web.1]:    at com.facebook.presto.sql.parser.SqlBaseParser.queryNoWith(SqlBaseParser.java:3126)
2016-12-02T00:09:04.628855+00:00 app[web.1]:    at com.facebook.presto.sql.parser.SqlBaseParser.query(SqlBaseParser.java:2599)
2016-12-02T00:09:04.628853+00:00 app[web.1]:    at com.facebook.presto.sql.parser.SqlBaseParser.queryTerm(SqlBaseParser.java:3270)
2016-12-02T00:09:04.628852+00:00 app[web.1]:    at com.facebook.presto.sql.parser.SqlBaseParser.queryPrimary(SqlBaseParser.java:3458)
2016-12-02T00:09:04.628855+00:00 app[web.1]:    at com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:1273)
2016-12-02T00:09:04.628856+00:00 app[web.1]:    at com.facebook.presto.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:231)
2016-12-02T00:09:04.628857+00:00 app[web.1]:    at com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:92)
2016-12-02T00:09:04.628858+00:00 app[web.1]:    at com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:65)
2016-12-02T00:09:04.628858+00:00 app[web.1]:    at org.rakam.report.QueryExecutorService.buildQuery(QueryExecutorService.java:170)
2016-12-02T00:09:04.628859+00:00 app[web.1]:    at org.rakam.postgresql.report.PostgresqlPseudoContinuousQueryService.create(PostgresqlPseudoContinuousQueryService.java:47)
2016-12-02T00:09:04.628861+00:00 app[web.1]:    at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
2016-12-02T00:09:04.628860+00:00 app[web.1]:    at org.rakam.analysis.realtime.RealTimeHttpService.createTable(RealTimeHttpService.java:65)
2016-12-02T00:09:04.628861+00:00 app[web.1]:    at org.rakam.server.http.JsonParametrizedRequestHandler.handleInternal(JsonParametrizedRequestHandler.java:126)
2016-12-02T00:09:04.628862+00:00 app[web.1]:    at org.rakam.server.http.JsonParametrizedRequestHandler.lambda$handle$1(JsonParametrizedRequestHandler.java:90)
2016-12-02T00:09:04.628859+00:00 app[web.1]:    at org.rakam.analysis.RealtimeService.create(RealtimeService.java:101)
2016-12-02T00:09:04.628863+00:00 app[web.1]:    at org.rakam.server.http.RakamHttpRequest.handleBody(RakamHttpRequest.java:232)
2016-12-02T00:09:04.628863+00:00 app[web.1]:    at org.rakam.server.http.HttpServerHandler.channelRead(HttpServerHandler.java:92)
2016-12-02T00:09:04.628864+00:00 app[web.1]:    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
2016-12-02T00:09:04.628864+00:00 app[web.1]:    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
2016-12-02T00:09:04.628865+00:00 app[web.1]:    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
2016-12-02T00:09:04.628866+00:00 app[web.1]:    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
2016-12-02T00:09:04.628866+00:00 app[web.1]:    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147)
2016-12-02T00:09:04.628867+00:00 app[web.1]:    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
2016-12-02T00:09:04.628867+00:00 app[web.1]:    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
2016-12-02T00:09:04.628868+00:00 app[web.1]:    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
2016-12-02T00:09:04.628868+00:00 app[web.1]:    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
2016-12-02T00:09:04.628869+00:00 app[web.1]:    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
2016-12-02T00:09:04.628870+00:00 app[web.1]:    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
2016-12-02T00:09:04.628870+00:00 app[web.1]:    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
2016-12-02T00:09:04.628871+00:00 app[web.1]:    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
2016-12-02T00:09:04.628871+00:00 app[web.1]:    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
2016-12-02T00:09:04.628872+00:00 app[web.1]:    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
2016-12-02T00:09:04.628873+00:00 app[web.1]:    at java.lang.Thread.run(Thread.java:745)
2016-12-02T00:09:04.628874+00:00 app[web.1]: Caused by: org.antlr.v4.runtime.NoViableAltException
2016-12-02T00:09:04.628875+00:00 app[web.1]:    at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:486)
2016-12-02T00:09:04.628875+00:00 app[web.1]:    at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:1886)
2016-12-02T00:09:04.628880+00:00 app[web.1]:    at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:412)
2016-12-02T00:09:04.628881+00:00 app[web.1]:    at com.facebook.presto.sql.parser.SqlBaseParser.selectItem(SqlBaseParser.java:4662)
2016-12-02T00:09:04.628882+00:00 app[web.1]:    ... 34 more
```

**Comment by buremba** [comment]
It should be working fine now.
