### ISSUE TITLE
Cannot add reports to dashboard without all variables selected

### ISSUE THREAD

**Issue by evelant** [rakam-io/rakam-ui#43]
This gives a non intuitive error message ```directive body parameter is required```
```
POST https://app.rakam.io/ui/dashboard/add_item 400 ()
(anonymous) @ raven.js:1107
(anonymous) @ angular.min.js:94
g @ angular.min.js:90
c @ angular.min.js:87
(anonymous) @ angular.min.js:121
$eval @ angular.min.js:135
$digest @ angular.min.js:132
$apply @ angular.min.js:135
(anonymous) @ angular.min.js:259
De @ angular.min.js:35
n @ angular.min.js:35
wrapped @ raven.js:372
2angular.min.js:108 TypeError: Cannot read property '0' of undefined
    at https://app.rakam.io/static/dist/scripts/app-00f1bf8bac9299f1b034.js:776:27519
    at Array.map (native)
    at h.directives (https://app.rakam.io/static/dist/scripts/app-00f1bf8bac9299f1b034.js:776:27486)
    at fn (eval at compile (https://app.rakam.io/static/dist/scripts/app-00f1bf8bac9299f1b034.js:4:19494), <anonymous>:4:490)
    at https://app.rakam.io/static/dist/scripts/app-00f1bf8bac9299f1b034.js:3:800
    at h.$digest (https://app.rakam.io/static/dist/scripts/app-00f1bf8bac9299f1b034.js:3:7864)
    at h.$apply (https://app.rakam.io/static/dist/scripts/app-00f1bf8bac9299f1b034.js:3:9465)
    at r (https://app.rakam.io/static/dist/scripts/app-00f1bf8bac9299f1b034.js:2:17467)
    at m (https://app.rakam.io/static/dist/scripts/app-00f1bf8bac9299f1b034.js:2:19601)
    at XMLHttpRequest.w.onload (https://app.rakam.io/static/dist/scripts/app-00f1bf8bac9299f1b034.js:2:20147)
    at XMLHttpRequest.wrapped (https://app.rakam.io/static/components/raven-js/dist/raven.js:372:29)
```

**Comment by buremba** [comment]
I could not repreduce the error. Which option did you select, unset, static or variable? If you can share a screenshot or explain the scenario, that would be great.

**Comment by buremba** [comment]
Closing due to inactivity. Please open the issue again if you still see this bug.
